### ISSUE TITLE
Smiley-Lib

### ISSUE THREAD

**Issue by DaAndi82** [foxdrodd/SIM#12]
Eine kleine Smiley-Library die Zeichen wie ";)" in ein entsprechendes Zeichen ersetzt wäre nice to have!

**Comment by foxdrodd** [comment]
Habe einen kleinen proof gemacht - siehe https://github.com/anrub/SIM/commit/53fd0fb3058186f2fe077f4d2332bf3af1c00a33 . 
Und die Smilies von Mozilla thunderbird eingebunden (oberer google treffer, deshalb) 

Wäre aber cool wenn du dich dem annimmst, so als Chief Smiley Officer oder so ;)

**Comment by DaAndi82** [comment]
Sehr cool! Ich werd mich dem heut annehmen!

**Comment by DaAndi82** [comment]
Ich würde das Yahoo Smiley Pack nehmen,... das ist CC (Creative Commons Lizenz)
http://creativecommons.org/licenses/by-nc/3.0/de/

Das sollte doch rechtlich passen oder?
http://stackoverflow.com/questions/802081/using-an-icon-under-gpl-or-lgpl-licence-for-commercial-web-design-work

**Comment by foxdrodd** [comment]
joa, sollte schon passen.

**Comment by DaAndi82** [comment]
Hab die Yahoo-Smiley's eingebaut.
