### ISSUE TITLE
User-Status

### ISSUE THREAD

**Issue by DaAndi82** [foxdrodd/SIM#17]
Jeder User soll seinen Status pflegen können.

**Comment by DaAndi82** [comment]
Zur Diskussion: Bei Änderung des Statuses vielleicht eine System-Nachricht?

**Comment by foxdrodd** [comment]
Gibts eigentlich, d.h. es wird eine Message an alle mit dem Userstatus gesendet. Für dich selbst wird das allerdings nicht angezeigt. (d.h nur "die andern" bekommen die message zu sehen)

**Comment by DaAndi82** [comment]
Ah ok! Wenns funzt kannst es ja schließen! ;)
