### ISSUE TITLE
Smileys: beim Mouseover evtl das kürzel anzeigen

### ISSUE THREAD

**Issue by foxdrodd** [foxdrodd/SIM#28]
.. um den smilie zu erzeugen

**Comment by DaAndi82** [comment]
Nicht lieber gleich ein popup einbaun (Neben dem Eingabefeld vielleicht) um Smiley per Mausklick einzufügen?

**Comment by foxdrodd** [comment]
so a popppab is drin. tooltip im message-feld zeigt er leider nicht an (also title/alt tag des img)
