### ISSUE TITLE
Allgemeine Verbesserungen

### ISSUE THREAD

**Issue by foxdrodd** [foxdrodd/SIM#4]
Gruppenchat wäre cool
Dateien versenden wäre cool

(Kein Autoscrolling im Fenster wenn neue Nachricht reinkommt vorhanden)

Umbrüche vielleicht mit SHIFT-Enter?
Unterschiedliche Farben für die Chat-Partner
Wozu ist der Cancel-Button?
"Ein Partner schreibt  gerade"

**Comment by DaAndi82** [comment]
Wurde in einzelne Issues aufgeteilt.
