### ISSUE TITLE
Online offline messages stimmen nicht immer

### ISSUE THREAD

**Issue by foxdrodd** [foxdrodd/SIM#8]

**Comment by DaAndi82** [comment]
Ich wäre auch dafür die On-/Offlinemeldungen im Chatfenster mit der jeweiligen Person anzuzeigen (nicht nur Stream). Denn wenn ich grad in dem Fenster was schreiben will oder nicht gleich sehe dass im Stream der User Offline ist, dann seh ichs gleich.

**Comment by foxdrodd** [comment]
ist jetz so eingebaut

**Comment by foxdrodd** [comment]
stimmt manchmal immernoch nicht

**Comment by foxdrodd** [comment]
REfreshingUserService.refresh wird 2 mal aufgerufen und startet dadurch 2 timer, muss auf 1 aufruf gefixt werden

**Comment by foxdrodd** [comment]
durch synchronized usw sollte es nun passen.
