### ISSUE TITLE
Autoscrollingprobleme

### ISSUE THREAD

**Issue by DaAndi82** [foxdrodd/SIM#9]
Das Autoscrolling funktioniert nicht immer korrekt.
- manchmal scrollt er gar nicht
- manchmal nicht ganz bis unten

**Comment by foxdrodd** [comment]
sollte gelöst sein, kannst dir ja mal pullen und den aktuellsten stand testen

**Comment by DaAndi82** [comment]
Sieht gut aus,... bei mir scrollt er runter.

**Comment by DaAndi82** [comment]
Revidiere, besteht leider weiterhin!

**Comment by foxdrodd** [comment]
hab nochmal was gefixt..

**Comment by foxdrodd** [comment]
gibt noch probs, wenn die größe des fensters geändert wird

**Comment by DaAndi82** [comment]
Also bei mir siehts gut aus,... auch nach ändern der Fenstergröße!

**Comment by DaAndi82** [comment]
Hm,... doch noch was gefunden,... im Fenster Stream klappts leider gar nicht mehr bei mir!
